---
functional:
  - У пользователя должна быть возможность зарегистрироваться и авторизоваться в системе.
  - Должна быть возможность авторизации через GitHub.
  - Должна быть возможность создать игру как с ботом, так и с другими игроками.
  - Должна быть возможность создать как приватную игру с конкретным игроком, так и публичную.
  - Должна быть возможность присоедениться к открытой игре.
  - Оба игрока должны получать одинаковое задание.
  - Задания должны даваться на двух языках - русском и английском
  - Решение задания должно быть представлено в виде кода.
  - Во время игры игроки должны видеть процесс написания кода соперником в реальном времени.
  - Система должна проверять правильность введенного решения с помощью автотестов.
  - Победителем считается первый игрок, решение которого удовлетворило автотесты.
  - Если оба игрока не справляются с задачей в установленное время -  игра завершается ничьей.
  - Завершенные игры должны быть доступны в записи.
  - За победу в игре должны начисляться очки рейтинга, за поражения должны сниматься.
  - На основе рейтинга должна составляться таблица лидеров с разными временными отрезками (неделя, месяц, за все время).
  - Во время игры должна быть возможность общаться с соперником и зрителями в чате.
  - Чат должен поддерживать отправку текстовых сообщений в реальном времени.
 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования.
  - Сайт долежн быть оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
implicit:
 - В чате должно быть ограничение на длинну сообщения, можно использовать только разрешенные символы и емоджи.
 - При регистрации должна быть проверка правильности почты и ее подтверждение.
 - Должна быть возможность просматривать онлайн пользователей и отправлять им приглашения в игру.
